# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QC2Bu3E3KEuO5AtTaDEpoDvDaKVIQY_i
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics opencv-python matplotlib

import os

# Define dataset path
dataset_path = "/content/drive/MyDrive/Object"

# Create dataset.yaml content
dataset_yaml_content = f"""path: {dataset_path}

train: train/images
val: valid/images

nc: 3  # Change this based on the number of classes
names: ["class1", "class2", "class3"]  # Replace with actual class names
"""

# Write to dataset.yaml
yaml_path = os.path.join(dataset_path, "dataset.yaml")

with open(yaml_path, "w") as yaml_file:
    yaml_file.write(dataset_yaml_content)

print(f"✅ dataset.yaml created at {yaml_path}")

from ultralytics import YOLO

# Load pre-trained YOLOv8 model
model = YOLO("yolov8s.pt")

# Train the model
model.train(data="/content/drive/MyDrive/Object/dataset.yaml",
            epochs=10, batch=16, imgsz=640)

import cv2
from ultralytics import YOLO

# Load trained model
model = YOLO("/content/yolo11n.pt")

# Path to test image
image_path = "/content/drive/MyDrive/Object/valid/images/clip_four_mp4-0032_jpg.rf.e21eb2efba5101dbf10079c83084fcae.jpg"

# Run object detection
results = model(image_path)

# Process each result in the list
for result in results:
    # Show the result
    result.show()

    # Save the output image
    result.save(filename="output.jpg")